name: currencypro
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Default icons asset for Cupertino widgets based on Apple styled icons
  cupertino_icons: ^1.0.8
  # A powerful HTTP networking package, for API request
  dio: ^5.4.3+1
  # state management Bloc design pattern. Built to be used with the bloc state management package
  flutter_bloc: ^8.1.5
  # A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  equatable: ^2.0.5
  # Easily create toast messages in single line of code
  fluttertoast: ^8.2.5
  # Flutter widgets for easily adding gaps inside Flex widgets such as Columns and Rows or scrolling views.
  gap: ^3.0.1
  # Functional Programming in Dart. Purify your Dart code using efficient immutable data structures, monads, lenses and other FP tools
  internet_connection_checker: ^1.0.0+1
  # for reading and writing simple key-value pairs. Wraps NSUserDefaults on iOS and SharedPreferences on Android.
  shared_preferences: ^2.2.3
  # Simple direct Service Locator that allows to decouple the interface from a concrete implementation and to access the concrete implementation from everywhere in your App
  get_it: ^7.7.0
  # Small, easy to use and extensible logger which prints beautiful logs.
  logger: ^2.2.0
  # A Flutter package to use fonts from fonts.google.com. Supports HTTP fetching, caching, and asset bundling.
  google_fonts: ^6.2.1
  # A set of useful sliver tools that are missing from the flutter framework
  sliver_tools: ^0.2.12
  # Contains code to deal with internationalized/localized messages, date and number formatting and parsing.
  intl: ^0.19.0
  # Easily add staggered animations to your ListView, GridView, Column and Row children as shown in Material Design guidelines
  flutter_staggered_animations: ^1.1.1
  # A collection of loading indicators animated with flutter. Heavily
  flutter_spinkit: ^5.2.1
  # A package provides an easy way to add shimmer effect in Flutter project
  shimmer: ^3.0.0
  # native splash screen with background color and splash image. Supports dark mode, full screen, and more.
  flutter_native_splash: ^2.4.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  # A command-line tool that simplifies the task of updating your Flutter app's launcher icon.
  icons_launcher: ^2.1.7

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #



